### ISSUE TITLE
Bitwarden.munki.recipe failing

### ISSUE THREAD

**Issue by eshirk** [autopkg/blackthroat-recipes#13]
Getting the following error when running the Bitwarden.munki recipe:

GitHubReleasesInfoProvider: Error: No release assets were found that satisfy the criteria.

(Bitwarden.download.recipe *does* work.)

Thanks--

**Comment by blackthroat** [comment]
@eshirk Are you still having an issue? I just ran the .munki recipe with no problems.

**Comment by eshirk** [comment]
@blackthroat , I just tried again and I'm still getting the same error with an override of your .munki recipe. I ended up using drewdiver's .download recipe (https://github.com/autopkg/drewdiver-recipes/blob/master/Bitwarden/Bitwarden.download.recipe) and making my own .munki recipe, and that does work. Thanks for checking in.
