### ISSUE TITLE
Plist error in Loopback.munki.recipe

### ISSUE THREAD

**Issue by eshirk** [autopkg/blackthroat-recipes#16]
Seeing the following in our CI workflow:

WARNING: plist error for /Users/Shared/AutoPkg/RecipeRepos/com.github.autopkg.blackthroat-recipes/Rogue Amoeba Software, Inc./Loopback.munki.recipe: unexpected key at line 39

Looks like a missing closing string tag.

**Comment by blackthroat** [comment]
@eshirk Should be fixed now. Thanks for the heads up!
